# Generated by Django 3.2.23 on 2024-01-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_auto_20240124_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Label Name'),
        ),
    ]
