# Generated by Django 3.2.23 on 2024-01-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_auto_20240125_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя'),
        ),
    ]
