# Generated by Django 3.2.23 on 2024-01-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20240125_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='performer',
            new_name='executor',
        ),
    ]
